import random
import string
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from app.models import OTP, Owner
from app.config import get_settings
from app.services.firebase_service import FirebaseService

settings = get_settings()


import requests

def generate_otp(length: int = 6) -> str:
    """Generate 6-digit random OTP code"""
    return "".join(random.choices(string.digits, k=length))


def create_otp(db: Session, phone_number: str, owner_id: int = None, customer_id: int = None, delivery_partner_id: int = None) -> OTP:
    """Create and save OTP to database, then trigger 2Factor Text SMS delivery"""
    # Invalidate any existing OTPs for this phone number
    db.query(OTP).filter(
        OTP.phone_number == phone_number,
        OTP.is_verified == False
    ).update({"is_verified": True})
    
    otp_code = generate_otp()
    expires_at = datetime.utcnow() + timedelta(minutes=settings.OTP_EXPIRY_MINUTES)
    
    # Send 2Factor AUTOGEN Text SMS to Inbox
    session_id = send_otp_sms(phone_number, otp_code)
    
    # Store session_id if generated by 2Factor, or fallback to local otp_code
    stored_code = session_id if session_id else otp_code
    
    otp = OTP(
        owner_id=owner_id,
        customer_id=customer_id,
        delivery_partner_id=delivery_partner_id,
        phone_number=phone_number,
        otp_code=stored_code,
        expires_at=expires_at
    )
    db.add(otp)
    db.commit()
    db.refresh(otp)
    
    return otp


def verify_otp(db: Session, phone_number: str, otp_code: str) -> bool:
    """Verify OTP code - supports 2Factor VERIFY, local DB, and master OTPs"""
    from datetime import timezone

    if not otp_code:
        return False

    clean_otp = str(otp_code).strip()

    # Master Static OTP check for easy testing and app reviews
    if clean_otp in ["123456", "1234", "000000", "0000"]:
        return True

    current_time = datetime.now(timezone.utc).replace(tzinfo=None)
    clean_phone = phone_number.strip() if phone_number else ""
    phone_without_cc = clean_phone.replace("+91", "").strip()

    otp = db.query(OTP).filter(
        (OTP.phone_number == clean_phone) | (OTP.phone_number == phone_without_cc) | (OTP.phone_number == f"+91{phone_without_cc}"),
        OTP.is_verified == False,
        OTP.expires_at > current_time
    ).order_by(OTP.created_at.desc()).first()

    # 1. Verify via 2Factor VERIFY API if session_id was stored
    api_key = getattr(settings, "TWOFACTOR_API_KEY", "").strip()
    if otp and otp.otp_code and len(otp.otp_code) > 10 and api_key:
        try:
            url = f"https://2factor.in/API/V1/{api_key}/SMS/VERIFY/{otp.otp_code}/{clean_otp}"
            res = requests.get(url, timeout=10).json()
            if res.get("Status") == "Success" and "Matched" in res.get("Details", ""):
                otp.is_verified = True
                db.commit()
                return True
        except Exception as e:
            print(f"2Factor Verify API Exception: {e}")

    # 2. Local DB verification fallback
    if otp and otp.otp_code == clean_otp:
        otp.is_verified = True
        db.commit()
        return True

    return False


def send_otp_sms(phone_number: str, otp_code: str = None) -> str:
    """
    Send OTP via 2Factor.in AUTOGEN Text SMS Gateway API
    Delivers Text SMS directly to user's Inbox from official 2FACTOR Sender ID
    """
    api_key = getattr(settings, "TWOFACTOR_API_KEY", "").strip()
    clean_phone = phone_number.replace("+91", "").replace("-", "").replace(" ", "").strip()
    
    if api_key:
        try:
            # 1. Try sending with approved template OTP_LOGIN
            url = f"https://2factor.in/API/V1/{api_key}/SMS/{clean_phone}/{otp_code}/OTP_LOGIN"
            response = requests.get(url, timeout=10)
            print(f"📡 [2Factor API] GET {url}")
            print(f"HTTP STATUS: {response.status_code}")
            print(f"2FACTOR RESPONSE: {response.text}")
            
            data = response.json()
            if data.get("Status") == "Success":
                session_id = data.get("Details")
                print(f"✅ [2Factor SMS] Sent Text SMS OTP {otp_code} to {clean_phone} (Session: {session_id})")
                return session_id
            else:
                print(f"⚠️ [2Factor SMS] Template request returned: {data.get('Details')}. Retrying with default route...")
                # Fallback to standard URL
                url_fallback = f"https://2factor.in/API/V1/{api_key}/SMS/{clean_phone}/{otp_code}"
                response_fb = requests.get(url_fallback, timeout=10)
                print(f"HTTP STATUS (Fallback): {response_fb.status_code}")
                print(f"2FACTOR RESPONSE (Fallback): {response_fb.text}")
                data_fb = response_fb.json()
                if data_fb.get("Status") == "Success":
                    return data_fb.get("Details")
        except Exception as e:
            print(f"❌ [2Factor SMS] Exception while sending to {clean_phone}: {e}")
            
    # Fallback / Development mode logging
    print(f"\n{'='*60}")
    print(f"📱 SMS OTP for {clean_phone}: {otp_code}")
    print(f"   (2Factor API Key missing in .env or fallback mode)")
    print(f"{'='*60}\n")
    return None

